name: pull request validation

on: pull_request

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "22.x"

      - name: Cache dependencies
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
  build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: npm run build
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: npm run lint
      - run: npm run test
