name: Pull Request Validation

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: "25.x"

      - name: Cache dependencies
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Restore Cache Card List
        uses: actions/cache/restore@v6
        with:
          path: data/default-cards.jsonl
          key: default-cards.jsonl-${{ github.run_id }}
          restore-keys: |
            default-cards.jsonl-

      - run: npm ci
      - run: npm run cards
      - run: npm run build
      - run: npm run lint
      - run: npm run test
