name: Pull Request Validation

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5.0.0
        with:
          node-version: "22.x"

      - name: Cache dependencies
        uses: actions/cache@v4.3.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Restore Cache Card List
        uses: actions/cache/restore@v4.3.0
        with:
          path: data/default-cards.json
          key: default-cards.json-${{ github.run_id }}
          restore-keys: |
            default-cards.json-

      - run: npm ci
      - run: npm run cards
      - run: npm run build
      - run: npm run lint
      - run: npm run test
